import "../styles/globals.scss";
import Head from 'next/head';
import type { AppProps } from 'next/app';
import { ToasterContextProvider } from "../common/contexts/toaster";
import { Navbar, Nav, Container } from 'react-bootstrap';

function MyApp({ Component, pageProps }: AppProps) {
  return <>
    <Head>
      <meta name="viewport" content="initial-scale=1, width=device-width" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Navbar bg="dark" variant="dark" expand="lg">
      <Container>
        <Navbar.Brand href="/">Arcade</Navbar.Brand>
        <Nav className="me-auto">
          <Nav.Link href="/games/sudoku">Sudoku</Nav.Link>
          <Nav.Link href="/games/wordGame">Word Game</Nav.Link>
        </Nav>
      </Container>
    </Navbar>
    <ToasterContextProvider>
      <Component {...pageProps} />
    </ToasterContextProvider>
  </>
}

export default MyApp
